#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define TELEMETRY_PERIOD_MS 100U
#define SENSOR_QUEUE_LENGTH 8U
#define VOLTAGE_UV_LIMIT_MV 2800U
#define VOLTAGE_OV_LIMIT_MV 3630U
#define CURRENT_OC_LIMIT_MA 2000U
#define TEMPERATURE_OT_LIMIT_C 85U

#endif
